development: &default
  adapter: postgresql
  database: ichacze_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  host: localhost
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>

test:
  <<: *default
  database: ichacze_test
